spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TEST
    username: POSTGRES
    password: POSTGRES
    driverClassName: org.postgresql.Driver
  profiles:
    active: local
    include: swagger

scheduling:
  ordersSchedule:
    enabled: false
    interval: 10000

logging:
  appenders:
    file:
      path: log

aspect:
  maxHistory: 300
  appender:
    database:
      enabled: false

