spring:
  application:
    name: my-app
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: POSTGRES
    password: POSTGRES
    driverClassName: org.postgresql.Driver
  profiles:
    active: local
    include: swagger

scheduling:
  ordersSchedule:
    enabled: true
    interval: 10000
