server:
  port: ${APP_PORT:8080}
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /
    application-display-name: MyAPP
  tomcat:
    max-connections: 1000
    accept-count: 100
    connection-timeout: 30000

spring:
  application:
    name: Book store
  datasource:
    url: jdbc:postgresql://localhost:5432/TEST
    username: POSTGRES
    password: POSTGRES
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      hbm2ddl:
        auto: none
      default_schema: public
      use_sql_comments: true
      format_sql: true

logging:
  level:
    ROOT: INFO
    com.aleksandr0412.bookstore: DEBUG
    org.springframework: INFO
  appenders:
    console:
      enabled: true


management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: true

threadPool:
  corePoolSize: 4
  maxPoolSize: 8

swagger:
  title: Book store
  description: API для проекта
  contact:
    mail: al.petrov@i-teco.ru
    name: Александр Петров
    url: https://github.com/Aleksandr0412/SpringLessons

